### ISSUE TITLE
Javadoc fails to build

### ISSUE THREAD

**Issue by hinerm** [Rocsg/FijiRelax#12]
**Describe the bug**
When running `mvn javadoc:javadoc` (or any goal that includes [jar](https://github.com/Rocsg/FijiRelax/blob/7883c512d2356612d8c11bf51222a862d8c87f54/pom.xml#L234-L239)) the javadoc fails to build with several errors about malformed javadoc.

**To Reproduce**
1. Clone repo
2. Navigate to repo basedir
3. Run `mvn clean install`

**Expected behavior**
The build should pass, including javadoc generation.

**Screenshots**
![image](https://user-images.githubusercontent.com/1123809/209167778-7a0fcd63-b7ef-407c-b8ba-b629e776d809.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
This likely started failing when you added [pom-scijava as a parent](https://github.com/Rocsg/FijiRelax/commit/b0688c48aff01c3647c76f13191f40bb58811cfa), as I believe it adds some more strict tests (that can be annoying but are meant to be helpful!).

The javadoc failure message should give you a complete list of what needs to be done. Many of the issues are just link problems (e.g. using `<a href="url">link</a>` instead of `<link>`, or importing/using a fully qualified path with `@throws`).

Several of these show up in your license header, so I wanted to mention that you can also remove the existing headers and then auto-generate them with:
```
mvn license:update-file-header
```

Then you can re-run this command in the future and it will e.g. auto-update the copyright year.

**Comment by Rocsg** [comment]
Hello Mark. I setup a "hard fix", by replacing html code with unoffensive literals. 
About the automatic licensing, I have to train a bit ; as FijiRelax license are specific, there is external source code (LMA), with specific headers. However, I will try mvn license: for Fijiyama plugin which is more straightforward for a start, and where I need to reproduce this CI setup
