### ISSUE TITLE
Consider using SNAPSHOT versioning

### ISSUE THREAD

**Issue by hinerm** [Rocsg/FijiRelax#16]
**Is your feature request related to a problem? Please describe.**
Currently your `pom.xml` declares a [release version](https://github.com/Rocsg/FijiRelax/blob/7883c512d2356612d8c11bf51222a862d8c87f54/pom.xml#L43). From a Maven perspective, there can only be one "true" release, but from a Git perspective, many commits now point to the same "release".

**Describe the solution you'd like**
Adding a `-SNAPSHOT` modifier to the version property in your `pom.xml` on non-release commits provides a clear delineation between release and non-release commits, and allows you to leverage the natural Maven machinery for releasing to Release or Snapshot repositories.

You can read more: [here](https://imagej.net/develop/maven#releases-and-snapshots) and [here](https://www.baeldung.com/maven-snapshot-release-repository) as a starting point.

**Describe alternatives you've considered**
Just incrementing the version when releasing and not using `-SNAPSHOT` is still a valid development style. One can still deduce the commit that corresponds to a release e.g., by looking at the "Implementation-build" in the jar's `MANFIEST.MF`, but it may not be obvious for many, and precludes the ability to deploy intermediate builds between versions.

**Comment by Rocsg** [comment]
Hi @hinerm ,
I setup this new behaviour for both Fijiyama (4.0.7-SNAPSHOT) and FijiRelax (4.0.9-SNAPSHOT). I bet I can go on on snapshots for a while, and when wanting to "fix" things, can deploy and tag releases 4.0.7 and 4.0.9 , then go on working, but on 4.0.8-SNAPSHOT and 4.0.10-SNAPSHOT 

Another thing, now that maven repository can be "overwritten" at any time, I should consider to automatically push to maven rep and sites.imagej.net/Fijiyama  from github action. I need to learn more about it, to estimate the "balance" in term of client risk. I set an issue for it.

Thank you again.
