### ISSUE TITLE
GUI not well displayed in Windows 16" screen

### ISSUE THREAD

**Issue by kasasxav** [Rocsg/FijiRelax#6]
**Describe the bug**

**To Reproduce**
1. Go to 'Graphical Explorer'

**Expected behavior**
All buttons should be displayed in the GUI.

**Screenshots**

<img width="1280" alt="gui_fijiRelax" src="https://user-images.githubusercontent.com/35917480/208214509-f733d598-3379-465c-83c2-d9b0976de33d.png">

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by Rocsg** [comment]
Thank you @kasasxav for this documented feedback. 

At GUI design time, we were maybe too focused on people using large screens, but there is a growing proportion of people working on ultra-portables, in locations that are unpredictable (my advisor do this, as well). I'll try to configure my laptop screen to reproduce this one (it is a matter of #pixels available width X height, I guess), and then publish a patch very soon.

**Comment by Rocsg** [comment]
Hello @kasasxav ,
I reproduced your bug using a low resolution mode, then made a fix for the case of small screens. It should activate automatically when you run the explorer with a small screen (width <= 1600). A popup() should appear just before explorer launch to inform that you're running in lowres mode.

To get the release, you can make Fiji > Help > Update, and apply the proposed update (fijirelax.jar) 
Let me know if everything is ok!

**Comment by kasasxav** [comment]
Still not working sorry :L But my screen is a bit weird, I have a laptop that is 16" (usually they are 15.6"). 
For me if you could include a way of manually adjusting the size of each widget would work (similar to qt with <>)
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/35917480/208757393-b38c967e-c146-4618-9be3-1b27f379c4f9.png">
