### ISSUE TITLE
Consider adding pom-scijava as a parent pom

### ISSUE THREAD

**Issue by hinerm** [Rocsg/FijiRelax#7]
**Is your feature request related to a problem? Please describe.**
Manually specifying dependency versions can lead to skew with what is shipped by Fiji.

**Describe the solution you'd like**
Define a [parent](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#Project_Inheritance) section in your [pom.xml](https://github.com/Rocsg/FijiRelax/blob/master/pom.xml), pointing to [pom-scijava](https://github.com/scijava/pom-scijava). You should be able to remove most `<version>` tags in your dependencies (for any that are managed by `pom-scijava`), as well as the `<repositories>` block.

**Describe alternatives you've considered**
The current mechanism of not inheriting from `pom-scijava` is fine, it just requires more maintenance to update component versions, and has a higher chance of not being compatible with some component shipped with Fiji

**Comment by Rocsg** [comment]
Hello @hinerm ,
We worked on the exact setup you proposed. It seems to be going well. You will find it in the release 4.0.8
