### ISSUE TITLE
Add Support section in README.md

### ISSUE THREAD

**Issue by hinerm** [Rocsg/FijiRelax#8]
**Is your feature request related to a problem? Please describe.**
There isn't an immediately obvious path to support, particularly for non-technical users not familiar with GitHub.

**Describe the solution you'd like**
A **Support** section in the `README.md` makes it clear what users should do for technical support. I recommend making a `fiji-relax` tag on [the ImageJ forum](https://forum.image.sc/) and linking to that in the Support section.

**Describe alternatives you've considered**
With no Support section the implicit default is to use GitHub issues. This is great but may not be clear for non-technical users. The ImageJ forum presents an area for discussion that may not meet the threshold of an "issue", and is also a more centralized option than an individual GitHub repo.

**Comment by Rocsg** [comment]
Hello @hinerm,
Thank you for this suggestion. We added a support section, following your suggestions. To date, the “support” procedure was to write a mail to me (my personnel mail appear there and there in the GUI). But it seems that it cannot be the single way to get support, and added official support, following your suggestions.
